version: '3'

services:
  backend:
    build: backend
    ports:
    - 8081:8081
    volumes:
    - ./backend:/backend
    - /nfs/geluid:/geluid
    #entrypoint: [ "/bin/sh", "-c", "sleep 2073600" ]

  frontend:
    build: frontend
    ports:
    - 8080:8080
    volumes:
    - ./frontend:/frontend
    #entrypoint: [ "/bin/sh", "-c", "sleep 2073600" ]

  proxy:
    image: nginx
    volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
    links:
    - backend:backend
    - frontend:frontend
    #entrypoint: [ "/bin/sh", "-c", "sleep 2073600" ]
